### ISSUE TITLE
Tests fail when building

### ISSUE THREAD

**Issue by kdopen** [GENIVI/franca_ara_tools#148]
I've followed the instructions at https://github.com/GENIVI/franca_ara_tools/wiki/FARACON-Developer-Guide but the build fails when executing the tests

```
Tests in error: 
  IDL1540_Tests.multipleNamedArrayTypesUsingTheSameElementType:60->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » ExceptionInInitializer
  IDL1540_Tests.namedArrayTypesWithElementsTypesFromDifferentNamespaces:74->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1540_Tests.complexNamedArrayType:34->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1540_Tests.namedArrayTypesWithImport:46->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1540_Tests.simpleNamedArrayType:24->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1620_Tests.multipleAnonymousArrayTypesUsingTheSameElementType:59->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1620_Tests.anonymousArrayTypesWithElementsTypesFromDifferentNamespaces:73->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1620_Tests.simpleAnonymousArrayType:23->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1620_Tests.complexAnonymousArrayType:33->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1620_Tests.anonymousArrayTypesWithImport:45->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  Franca2ARATests.testSimpleAttribute:32->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  Franca2ARATests.testSimpleBroadcast:37->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  Franca2ARATests.testSimpleMap:52->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  Franca2ARATests.testSimpleEnum:42->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  Franca2ARATests.testSimpleArray:47->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  Franca2ARATests.test_20:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1130_Tests.multipleInterfaces:23->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1130_Tests.oneInterface:18->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1100_Tests.emptyFile:18->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1110_Tests.namespacesHierarchy:18->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1140_Tests.oneTypeCollectionDefinition:18->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1140_Tests.multipleTypeCollectionDefinitions:23->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  CreateShowcaseARATests.createDrivingLaneARXML:19->Franca2ARATestBase.transform:39->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  CreateShowcaseARATests.createVehiclesARXML:24->Franca2ARATestBase.transform:39->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1800_Tests.predefinedBasicTypeMethodArguments:24->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1800_Tests.predefinedBasicTypeStructFields:29->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1810_Tests.userDefinedTypeStructFields:31->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1810_Tests.userDefinedTypeMethodArguments:23->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1690_Tests.testUnionWithBaseUnionToAutosarUnion:84->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1690_Tests.testUnionWithBaseUnionInNamedTypeCollectionToAutosarUnion:92->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1680_Tests.testSingleFrancaUnionToAutosarUnion:37->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1680_Tests.testMultipleFrancaUnionsToAutosarUnions:43->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1680_Tests.testUnionAndInterfaceInPackage:49->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastWithoutArguments:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastWithOneArgument:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastWithMultipleArguments:31->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastConflictWithUserStruct:36->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastDoubleConflictWithUserStructs:41->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastConflictWithUserEnum:46->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1380_Tests.broadcastNonConflictWithIdenticallyNamedMethod:51->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1250_Tests.oneBroadcast:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1250_Tests.multipleMethods:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  FrancaToAutosarStandardTypesTest.testFrancaBasicTypesInStruct:129->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  FrancaAutosarStdTypeFilesCreationTest.testAutosarStdFilesCreation:33->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  ARA2FrancaTests.test_20:25->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1125_Tests.testMultipleFrancaInputFilesWithMultipleInterfacesAndTypesWithImport:40->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1125_Tests.testMultipleFilesFromFrancaWithImport:26->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1125_Tests.testIncompleteFrancaInputModels:50->Franca2ARATestBase.transformAndCheckIntegrationTest:66 » NoClassDefFound
  IDL1480_Tests.testFrancaAnnotationToSdg:92->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1760_Tests.testMapTypeTransformation:23->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1760_Tests.testMapTypeUsageTransformation:31->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1240_Tests.multipleMethods:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1240_Tests.oneMethod:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1220_Tests.interfaceDefinition:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1270_Tests.interfaceInheritance:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1270_Tests.interfaceInheritanceWithContent:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1230_Tests.testMultipleFieldsToAttributes:30->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1230_Tests.testSingleFieldToAttribute:22->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1450_Tests.arrayMethodInputArgument:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1450_Tests.broadcastArgument:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1290_Tests.methodWithInAndOutArguments:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1310_Tests.oneMethodInputArgument:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1310_Tests.multipleMethodInputArguments:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1320_Tests.multipleMethodInputArguments:26->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1320_Tests.oneMethodReturnValue:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1300_Tests.fireAndForgetMethod:21->Franca2ARATestBase.transformAndCheck:47->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1660_Tests.testStructWithBaseStructInNamedTypeCollectionToAutosarStruct:92->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1660_Tests.testStructWithBaseStructToAutosarStruct:84->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1650_Tests.testSingleFrancaStructToAutosarStruct:37->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1650_Tests.testMultipleFrancaStructToAutosarStruct:43->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1650_Tests.testStructAndInterfaceInPackage:49->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1490_Tests.testFInterfaceWithVersion:78->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1190_Tests.testTypeCollectionUsageWithVersion:111->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1580_Tests.testTypeDefToAutosarTransformation:61->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1730_Tests.testCreateEnumerationTypeFromImplementationDataType:69->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound
  IDL1720_Tests.testCreateEnumerationTypeFromImplementationDataType:79->Franca2ARATestBase.transformAndCheck:51->Franca2ARATestBase.transformtionTest:109 » NoClassDefFound

Tests run: 230, Failures: 0, Errors: 76, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Franca ARA Converter 0.9.0-SNAPSHOT:
[INFO] 
[INFO] Franca ARA Converter ............................... SUCCESS [  1.186 s]
[INFO] org.genivi.faracon.targetplatform .................. SUCCESS [  0.098 s]
[INFO] org.genivi.faracon ................................. SUCCESS [ 18.475 s]
[INFO] org.genivi.faracon.console ......................... SUCCESS [  1.187 s]
[INFO] org.genivi.faracon.cli ............................. SUCCESS [  1.883 s]
[INFO] org.genivi.faracon.eclipse.ui ...................... SUCCESS [  2.156 s]
[INFO] org.genivi.faracon.tests ........................... FAILURE [ 44.190 s]
[INFO] org.genivi.faracon.feature ......................... SKIPPED
[INFO] org.genivi.faracon.console.franca.feature .......... SKIPPED
[INFO] org.genivi.faracon.console.feature ................. SKIPPED
[INFO] org.genivi.faracon.cli.feature ..................... SKIPPED
[INFO] org.genivi.faracon.eclipse.ui.feature .............. SKIPPED
[INFO] org.genivi.faracon.cli.product ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:26 min
[INFO] Finished at: 2019-12-18T21:33:02-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (test) on project org.genivi.faracon.tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/keith/play/VSS/franca_ara_tools/tests/org.genivi.faracon.tests/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.genivi.faracon.tests
```

My environment is Ubuntu 18.04.3 LT, with `mvn -v` reporting

```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-70-generic", arch: "amd64", family: "unix"
```

**Comment by gvergine** [comment]
Hello,

I just tried to build ```master/HEAD``` (db2e55e0576dd479e8ab50ff153c9a969e211791) following the wiki, and it works for me.

My environment:

```
mvn -v

Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-37-generic", arch: "amd64", family: "unix"

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Comment by gvergine** [comment]
The problem is reproducible when building the tool behind a proxy, without the ```proxies``` section configured in the maven settings.xml.

Now the wiki is updated:

https://github.com/GENIVI/franca_ara_tools/wiki/FARACON-Developer-Guide#31-configure-a-proxy

However, I feel we need to find a way for maven to be more explicit about not having been able to download a dependency (something like the ```REQUIRED``` keyword in cmake's ```find_package``` directive)

**Comment by kdopen** [comment]
The only problem is ... I don't have a proxy configured

**Comment by gvergine** [comment]
> The only problem is ... I don't have a proxy configured

I understand that the problem is solved and the issue can be closed?

**Comment by gvergine** [comment]
The error seems to be related to this stacktrace

`
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 1.28 sec <<< FAILURE! - in org.genivi.faracon.tests.aspects_on_arrays.f2a.IDL1540_Tests
multipleNamedArrayTypesUsingTheSameElementType(org.genivi.faracon.tests.aspects_on_arrays.f2a.IDL1540_Tests)  Time elapsed: 0.48 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at org.eclipse.emf.ecore.xml.namespace.impl.XMLNamespacePackageImpl.initializePackageContents(XMLNamespacePackageImpl.java:356)
	at org.eclipse.emf.ecore.xml.namespace.impl.XMLNamespacePackageImpl.init(XMLNamespacePackageImpl.java:128)
	at org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage.<clinit>(XMLNamespacePackage.java:69)
	at org.eclipse.sphinx.emf.resource.ExtendedXMLSaveImpl.addNamespaceDeclarations(ExtendedXMLSaveImpl.java:368)
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.traverse(XMLSaveImpl.java:607)
	at org.eclipse.sphinx.emf.resource.ExtendedXMLSaveImpl.traverse(ExtendedXMLSaveImpl.java:157)
	at org.eclipse.sphinx.emf.resource.ExtendedXMLSaveImpl.save(ExtendedXMLSaveImpl.java:121)
	at org.artop.aal.common.resource.impl.AutosarXMLResourceImpl.doSave(AutosarXMLResourceImpl.java:396)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:999)
	at org.genivi.faracon.ARAConnector.saveARXML(ARAConnector.java:180)
	at org.genivi.faracon.ARAConnector.saveARXML(ARAConnector.java:191)
	at org.genivi.faracon.ARAConnector.saveModel(ARAConnector.java:78)
	at org.genivi.faracon.cli.Franca2AraConverter$7.accept(Franca2AraConverter.java:205)
	at org.genivi.faracon.cli.Franca2AraConverter$7.accept(Franca2AraConverter.java:1)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.genivi.faracon.cli.Franca2AraConverter.saveAllGeneratedModels(Franca2AraConverter.java:208)
	at org.genivi.faracon.cli.AbstractFaraconConverter.convertModelContainersAndSaveResults(AbstractFaraconConverter.java:60)
	at org.genivi.faracon.cli.AbstractFaraconConverter.convertFiles(AbstractFaraconConverter.java:53)
	at org.genivi.faracon.tests.util.Franca2ARATestBase.transformAndCheckIntegrationTest(Franca2ARATestBase.java:66)
	at org.genivi.faracon.tests.aspects_on_arrays.f2a.IDL1540_Tests.multipleNamedArrayTypesUsingTheSameElementType(IDL1540_Tests.java:60)
`

That is same as this bug (scrool down to the comment from 30 Oct 2019 to see it)

[https://bugs.eclipse.org/bugs/show_bug.cgi?id=394659](https://bugs.eclipse.org/bugs/show_bug.cgi?id=394659)

**Comment by kdopen** [comment]
OK – well it’s 100% reproducible for me. And there’s no obvious workaround?

**Comment by MLanghammer** [comment]
Hi, 

we looked in to the problem. Unfortunately, we cannot reproduce it locally (and also not on the build server), yet.
If your goal is only to get an executable of the faracon-tool, you can use the following maven command to build the tool: 
`mvn clean install -Pwith-artop -DskipTests`

This will skip all tests and should create the executable. 

Best,
Michael

**Comment by kdopen** [comment]
I finally got a clean run of the full build: thanks to the "shelter in place" order I was able to bring my desktop home. It still didn't run initially ... but I did a fetch and pull and re-ran it and ti passed.

So, either 

* one of the 34 commits I pulled down fixed something (possibly by sing a newer version of some dependency)
* the pull caused a "clean" operation to be more thorough, wiping some cached (but wrong) intermediate artifact
* or there really is a proxy somewhere in my office network connection

If it's the latter, the proxy must be well hidden as we make absolutely no configuration changes on our machines to allow for it.

**Comment by kdopen** [comment]
Next problem, which may just be setup.

I used the VSS conversion tools to generate a .fidl file just for the ADAS vspec, then trie to covert it to ARXML. The converter crashed

```
$ faracon-linux-x86_64 -f ADAS.fidl 
Command: Franca ARA Converter
   Using ARA standard types path /home/keith/play/VSS/vehicle_signal_specification
Loading Franca IDL model input files...
   Loading FrancaIDL file /home/keith/play/VSS/vehicle_signal_specification/ADAS.fidl
Converting Franca IDL models to Adaptive AUTOSAR IDL models...
   Converting FrancaIDL file file:/home/keith/play/VSS/vehicle_signal_specification/ADAS.fidl
java.lang.NullPointerException
	at org.genivi.faracon.franca2ara.ARAModelSkeletonCreator._init_createPackageHierarchy(ARAModelSkeletonCreator.java:78)
	at org.genivi.faracon.franca2ara.ARAModelSkeletonCreator.createPackageHierarchy(ARAModelSkeletonCreator.java:71)
	at org.genivi.faracon.franca2ara.ARAModelSkeletonCreator._init_createAutosarModelSkeleton(ARAModelSkeletonCreator.java:57)
	at org.genivi.faracon.franca2ara.ARAModelSkeletonCreator.createAutosarModelSkeleton(ARAModelSkeletonCreator.java:50)
	at org.genivi.faracon.Franca2ARATransformation.transform(Franca2ARATransformation.java:106)
	at org.genivi.faracon.ARAConnector.fromFranca(ARAConnector.java:107)
	at org.genivi.faracon.cli.Franca2AraConverter$8.apply(Franca2AraConverter.java:252)
	at org.genivi.faracon.cli.Franca2AraConverter$8.apply(Franca2AraConverter.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at com.google.common.collect.Lists.newArrayList(Lists.java:128)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:600)
	at org.genivi.faracon.cli.Franca2AraConverter.transform(Franca2AraConverter.java:258)
	at org.genivi.faracon.cli.AbstractFaraconConverter.convertModelContainersAndSaveResults(AbstractFaraconConverter.java:98)
	at org.genivi.faracon.cli.AbstractFaraconConverter.convertFiles(AbstractFaraconConverter.java:85)
	at org.genivi.faracon.cli.ConverterCliCommand.convertFrancaFiles(ConverterCliCommand.java:126)
	at org.genivi.faracon.cli.ConverterCliCommand.execute(ConverterCliCommand.java:115)
	at org.genivi.faracon.cli.ConverterCliCommandHandler.execute(ConverterCliCommandHandler.java:31)
	at org.genivi.faracon.console.CommandExecuter$1.run(CommandExecuter.java:220)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.genivi.faracon.console.CommandExecuter.executeCommand(CommandExecuter.java:210)
	at org.genivi.faracon.console.internal.Application.start(Application.java:24)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
keith@FPD6GZ1-LNX:/home/.../VSS/vehicle_signal_specification$ ^C
keith@FPD6GZ1-LNX:/home/.../VSS/vehicle_signal_specification$ 
```
Am I missing something? Do I need to translate the entire VSS to a .fidl file?

**Comment by kdopen** [comment]
Nope -- same result if I pass it the full `.fidl` file from `make franca`

**Comment by MLanghammer** [comment]
Hi, 
I can reproduce the error. The fidl file you use seems not correct. It does not have a package/name, which leads the transformation to fail. 
As soon as the PR (https://github.com/GENIVI/franca_ara_tools/pull/155) is merged the nullpointer exception should be gone and replaced with a more useful error message.
Nevertheless, the transformation cannot be continued after the point, because the model is broken. In oder to fix that you can add a line "package foo.bar" at the top of the fidl file so that your model has a valid name/package.

Also I am not sure if the Franca file you provided earlier will go through the transformatin as it is incomplete, for instance, the import to UTF8String is missing. 
Can you provide the full fidl-file you are using?

**Comment by kdopen** [comment]
It is generated using `vspec2franca` from https://github.com/GENIVI/vehicle_signal_specification/tree/master/tools

I'm trying to get the toolchain to work from VSS specification -> franca -> ARXML

**Comment by kdopen** [comment]
OK. adding a package statement and commenting out the `VSS_VERSION` statement let the converter run ... it didn't generate much though.

But I can close this now.
