### ISSUE TITLE
NullPointerException while converting arxml to fidl

### ISSUE THREAD

**Issue by jhflow** [GENIVI/franca_ara_tools#90]
After building the tool (I disabled to avoid the issue https://github.com/GENIVI/franca_ara_tools/issues/89), I tried to convert both way (fidl to arxml, arxml to fidl) using interfaces included in tests/.
fidl to arxml works well, but the opposite direction ended w/ the following error:

	$ faracon-linux-x86_64 -a ./tests/org.genivi.faracon.tests/src-gen/testcases/vehicles.arxml
	Command: Franca ARA Converter
	java.lang.NullPointerException
	        at org.genivi.faracon.cli.FilePathsHelper.findFiles(FilePathsHelper.java:44)
	        at org.genivi.faracon.cli.ConverterCliCommand.execute(ConverterCliCommand.java:147)
	        at org.genivi.faracon.cli.ConverterCliCommandHandler.execute(ConverterCliCommandHandler.java:31)
	        at org.genivi.faracon.console.CommandExecuter$1.run(CommandExecuter.java:220)
	        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	        at org.genivi.faracon.console.CommandExecuter.executeCommand(CommandExecuter.java:210)
	        at org.genivi.faracon.console.internal.Application.start(Application.java:24)
	        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

I tested several files and got the same error.

**Comment by MLanghammer** [comment]
Hi, 

thanks a lot for testing the tool. I guess you tested with the current master (since you have not stated anything different). 

I already had a look at the error mentioned in this ticket and I guess this is easy to fix.
Once we fixed it, I will notify you.

Best,
Michael

**Comment by jhflow** [comment]
Dear Michael,

Exactly. I built and tested on master.
I look forward to good news :)

**Comment by MLanghammer** [comment]
Hi, 
the issue (and the other two you mentioned) are fixe in the upcoming 0.9 Release. Thanks again for reporting.
Best,
Michael
